### ISSUE TITLE
Can not use with webpack?

### ISSUE THREAD

**Issue by littlee** [serbanghita/formToObject.js#15]
I trying to require form_to_object,
`var fto = require('form_to_object')`
but always get this error:
Uncaught TypeError: fto is not a function

**Comment by serbanghita** [comment]
@littlee it's because I have removed the support for AMD, I will put it back and test and get back to you!

**Comment by littlee** [comment]
thanks

**Comment by serbanghita** [comment]
Found this old commit by @victorstanciu that I've removed because I couldn't tested it at the time:

```js
	// AMD/requirejs: Define the module
	if( typeof define === 'function' && define.amd ) {
	    define(function () {
	    	return formToObject;
    	});
	}
	// Browser: Expose to window
	else {
		window.formToObject = formToObject;
	}
```

Alternatively, if you are using require.js, you can load the module like this:
```html
<script>
	require(['formToObject'], function (formToObject) {
		// your code here
	});
</script>
```
@littlee can you test this code?

**Comment by littlee** [comment]
let me try it

**Comment by serbanghita** [comment]
I'm not on the computer and just pasted the text from an old commit. Can
you try it manually?

**Comment by serbanghita** [comment]
Done, check `npm install form_to_object`

**Comment by littlee** [comment]
I finally try to use form_to_object from npm

`npm install form_to_object`

but I get this Error when I require it:
```
Error: Cannot find module 'form_to_object'
```

my code:
```
var fto = require('form_to_object');
```

can you check that if you package is suit for npm publish ?

**Comment by serbanghita** [comment]
I'm having issues publishing a new version from my machine, see https://github.com/npm/npm/issues/9931#issuecomment-193233326

I will switch to mac and retry. Do you guys know any automated config so when I release a new version (tag) of formToObject it gets automatically published on https://www.npmjs.com/package/form_to_object?

**Comment by serbanghita** [comment]
I've pushed `1.0.8` to npm. Can you please check?
I need to write a test for node so we never have this problem again.

**Comment by littlee** [comment]
`1.0.8` works now, Thanks
