### ISSUE TITLE
wrong format multiple select?

### ISSUE THREAD

**Issue by Hunsziszi** [serbanghita/formToObject.js#20]
Hi,
Thanks for your work, its very helpful,  long time I'd been digging for this script.

I hava a little problem, when I send the form data via ajax, there are some difference according to the normal post send, if the form contain multiple select.

```
<select name="test[]" multiple>
        <option value="a" selected>a</option>
        <option value="b" selected>b</option>
</select>
```
Post array after sumit with normal form:
![image](https://user-images.githubusercontent.com/28574295/41641992-53cb535e-7467-11e8-8d21-7b91d103b525.png)

Post array after send ajax wtih formToObject data
![image](https://user-images.githubusercontent.com/28574295/41642013-6751458c-7467-11e8-8124-04298737b9bd.png)

**Comment by serbanghita** [comment]
Fixed in https://github.com/serbanghita/form-to-object/releases/tag/3.0.0-rc.0

It only took 5 years
