### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by tomByrer** [serbanghita/formToObject.js#7]
I'm not sure how to use this script.  I tried [using an existing form](https://github.com/maxatwork/form2js/blob/master/example/form2js.example.html), replacing the code at the end with this.
```html
<script type="text/javascript" src="formToObject.js"></script>
<!-- <script type="text/javascript" src="json2.js"></script> -->
<script type="text/javascript">
	function test()	{
		var formData = new formToObject('testForm');
		document.getElementById('testArea').innerHTML = formData;
	}
</script>
```

I only get `[object]` output.
Any tips or online examples please?

**Comment by serbanghita** [comment]
@tomByrer I know this is late, but here we go. I have included some basic examples on https://github.com/serbanghita/formToObject.js/blob/master/README.md

Thanks for pointing this out.
